import type { AlertEvent, FleetNode, FleetSnapshot, SensorSeries } from "./types";

export const nodes: FleetNode[] = [
  {
    id: "pond-guardian-07",
    name: "Pond Guardian 07",
    region: "Fujian Aquaculture",
    status: "warning",
    agent: "picclaw",
    lat: 24.88,
    lng: 118.67,
    uptimeHours: 438,
    cpu: 41,
    memory: 58,
    battery: 82,
    signal: 92,
    lastSeen: "18s ago",
    skill: "aquaculture-monitoring",
  },
  {
    id: "cold-chain-sz-03",
    name: "Cold Chain SZ 03",
    region: "Shenzhen Logistics",
    status: "online",
    agent: "nanoclaw",
    lat: 22.54,
    lng: 114.05,
    uptimeHours: 119,
    cpu: 29,
    memory: 46,
    battery: 100,
    signal: 88,
    lastSeen: "7s ago",
    skill: "cold-chain-compliance",
  },
  {
    id: "greenhouse-ber-11",
    name: "Greenhouse BER 11",
    region: "Berlin Trial",
    status: "online",
    agent: "microclaw",
    lat: 52.52,
    lng: 13.4,
    uptimeHours: 77,
    cpu: 22,
    memory: 31,
    battery: 64,
    signal: 73,
    lastSeen: "33s ago",
    skill: "greenhouse-climate",
  },
  {
    id: "warehouse-dfw-02",
    name: "Warehouse DFW 02",
    region: "Dallas Fulfillment",
    status: "critical",
    agent: "picclaw",
    lat: 32.78,
    lng: -96.8,
    uptimeHours: 13,
    cpu: 83,
    memory: 76,
    battery: 91,
    signal: 54,
    lastSeen: "4m ago",
    skill: "warehouse-guard",
  },
  {
    id: "machine-osaka-04",
    name: "Machine Doctor 04",
    region: "Osaka Plant",
    status: "offline",
    agent: "nanoclaw",
    lat: 34.69,
    lng: 135.5,
    uptimeHours: 0,
    cpu: 0,
    memory: 0,
    battery: 37,
    signal: 0,
    lastSeen: "31m ago",
    skill: "predictive-maintenance",
  },
  {
    id: "energy-madrid-01",
    name: "Energy Expert 01",
    region: "Madrid Microgrid",
    status: "online",
    agent: "picclaw",
    lat: 40.42,
    lng: -3.7,
    uptimeHours: 612,
    cpu: 34,
    memory: 49,
    battery: 96,
    signal: 81,
    lastSeen: "11s ago",
    skill: "energy-optimization",
  },
];

export const alerts: AlertEvent[] = [
  {
    id: "evt-9182",
    nodeId: "warehouse-dfw-02",
    nodeName: "Warehouse DFW 02",
    severity: "critical",
    title: "Vibration spike above shutdown threshold",
    description: "Compressor axis X reached 8.7 mm/s RMS for 42 seconds.",
    timestamp: "2m ago",
    acknowledged: false,
  },
  {
    id: "evt-9179",
    nodeId: "pond-guardian-07",
    nodeName: "Pond Guardian 07",
    severity: "warning",
    title: "Dissolved oxygen trending low",
    description: "DO dropped from 6.1 to 4.8 mg/L over the last hour.",
    timestamp: "9m ago",
    acknowledged: false,
  },
  {
    id: "evt-9171",
    nodeId: "machine-osaka-04",
    nodeName: "Machine Doctor 04",
    severity: "critical",
    title: "Node offline",
    description: "No heartbeat received for 31 minutes. Last OTA version 0.1.0.",
    timestamp: "31m ago",
    acknowledged: true,
  },
  {
    id: "evt-9166",
    nodeId: "cold-chain-sz-03",
    nodeName: "Cold Chain SZ 03",
    severity: "info",
    title: "Compliance report generated",
    description: "GSP export created for shipment SZ-8842.",
    timestamp: "46m ago",
    acknowledged: true,
  },
];

const seriesValues = (base: number, spread: number) =>
  Array.from({ length: 18 }, (_, index) => ({
    time: `${String(index + 6).padStart(2, "0")}:00`,
    value: Number((base + Math.sin(index / 2) * spread + (index % 4) * 0.18).toFixed(2)),
  }));

export const sensorSeries: SensorSeries[] = [
  {
    nodeId: "pond-guardian-07",
    metric: "dissolved_oxygen",
    unit: "mg/L",
    values: seriesValues(5.5, 0.65),
  },
  {
    nodeId: "cold-chain-sz-03",
    metric: "temperature",
    unit: "C",
    values: seriesValues(3.2, 0.45),
  },
  {
    nodeId: "warehouse-dfw-02",
    metric: "vibration",
    unit: "mm/s",
    values: seriesValues(5.8, 1.9),
  },
];

export const mockSnapshot: FleetSnapshot = {
  nodes,
  alerts,
  sensorSeries,
  updatedAt: new Date().toISOString(),
};
